<?xml version="1.0" encoding="utf-8"?><Database Name="EmployDB" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=EmployDB;Integrated Security=True" SettingsObjectName="SmsSupport.Properties.Settings" SettingsPropertyName="EmployDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_SmsReceived" Member="Tbl_SmsReceiveds">
    <Type Name="Tbl_SmsReceived">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsVisit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>